version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: sandwicher-domain
    ports:
      - '8000:80'
    volumes:
      - './:/app'
    networks:
      - sandwicher-network

networks:
  sandwicher-network:
      driver: bridge