version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        WWWUSER: '${WWWUSER}'
    image: sandwicher/domain
    container_name: sandwicher-domain
    volumes:
      - ./:/var/www
    ports:
      - "9000"
    networks:
      - sandwicher-network

networks:
  sandwicher-network:
    driver: bridge